dist: xenial

language: python

python:
  - 3.6
  - 3.7
  - nightly
  - pypy3.5-6.0
matrix:
  allow_failures:
    - python: nightly
install:
  - pip install -q -r dev-requirements.txt --no-cache-dir --upgrade
script:
  - make check_format
  - make test
after_success: codecov
